"""create_users_table

Revision ID: 5eb4eddc6010
Revises: 
Create Date: 2026-08-24 17:15:07.622255

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '5eb4eddc6010'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
